package qex

type AutoGenerated struct {
	Class   string `json:"_class"`
	Actions []struct {
		Class      string `json:"_class,omitempty"`
		Parameters []struct {
			Class string `json:"_class"`
			Name  string `json:"name"`
			Value string `json:"value"`
		} `json:"parameters,omitempty"`
		Causes []struct {
			Class            string `json:"_class"`
			ShortDescription string `json:"shortDescription"`
			UserID           string `json:"userId"`
			UserName         string `json:"userName"`
		} `json:"causes,omitempty"`
		BuildsByBranchName struct {
			RevisionInfoMap map[string]RevisionInfo
		} `json:"buildsByBranchName,omitempty"`
		LastBuiltRevision struct {
			Sha1   string `json:"SHA1"`
			Branch []struct {
				Sha1 string `json:"SHA1"`
				Name string `json:"name"`
			} `json:"branch"`
		} `json:"lastBuiltRevision,omitempty"`
		RemoteUrls []string `json:"remoteUrls,omitempty"`
		ScmName    string   `json:"scmName,omitempty"`
		FailCount  int      `json:"failCount,omitempty"`
		SkipCount  int      `json:"skipCount,omitempty"`
		TotalCount int      `json:"totalCount,omitempty"`
		URLName    string   `json:"urlName,omitempty"`
	} `json:"actions"`
	Artifacts []struct {
		DisplayPath  string `json:"displayPath"`
		FileName     string `json:"fileName"`
		RelativePath string `json:"relativePath"`
	} `json:"artifacts"`
	Building          bool        `json:"building"`
	Description       interface{} `json:"description"`
	DisplayName       string      `json:"displayName"`
	Duration          int         `json:"duration"`
	EstimatedDuration int         `json:"estimatedDuration"`
	Executor          interface{} `json:"executor"`
	FullDisplayName   string      `json:"fullDisplayName"`
	ID                string      `json:"id"`
	KeepLog           bool        `json:"keepLog"`
	Number            int         `json:"number"`
	QueueID           int         `json:"queueId"`
	Result            string      `json:"result"`
	Timestamp         int64       `json:"timestamp"`
	URL               string      `json:"url"`
	BuiltOn           string      `json:"builtOn"`
	ChangeSet         struct {
		Class string        `json:"_class"`
		Items []interface{} `json:"items"`
		Kind  string        `json:"kind"`
	} `json:"changeSet"`
	Culprits []interface{} `json:"culprits"`
}

type RevisionInfo struct {
	Class       string      `json:"_class"`
	BuildNumber int         `json:"buildNumber"`
	BuildResult interface{} `json:"buildResult"`
	Marked      struct {
		Sha1   string `json:"SHA1"`
		Branch []struct {
			Sha1 string `json:"SHA1"`
			Name string `json:"name"`
		} `json:"branch"`
	} `json:"marked"`
	Revision struct {
		Sha1   string `json:"SHA1"`
		Branch []struct {
			Sha1 string `json:"SHA1"`
			Name string `json:"name"`
		} `json:"branch"`
	} `json:"revision"`
}
