{
 "title": "QEX",
 "time": { "from": "now-168h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "productLine",
    "label": "Choose Product",
    "query": "sto, promotion, paidads, wsa, stock_price, order, user, rcmd"
   },
   {
    "name": "qa",
    "label": "Choose QA",
    "query": "Click-to-choose, keshia.yapkt@example.com, luohua.huang@example.com"
   }
  ]
 },
 "panels": [
  { "title": "All Product Lines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<center><h1 style=\"color:rgb(87, 147, 242);\">All Product Lines</h1></center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Cases Executed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE $timeFilter AND status=0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE $timeFilter AND status=1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE $timeFilter AND status=2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE (\"status\"=0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE (\"status\"=1) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE (\"status\"=2) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pass Rate By Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CUMULATIVE_SUM(COUNT(\"case\")) FROM \"all_records_v2\" WHERE (\"status\"=0) AND $timeFilter GROUP BY time($interval) fill(null) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CUMULATIVE_SUM(COUNT(\"case\")) FROM \"all_records_v2\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OKR Trends",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "alias": "AT Sign-off",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(DISTINCT(jira_id)) FROM \"all_jira_okr_records_v2\" WHERE (\"type\"=0) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "AT Found-bug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(DISTINCT(jira_id))  FROM \"all_jira_okr_records_v2\" WHERE (\"type\"=1) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Test Cases",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_git_records_v2 WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Sign-off Tickets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(jira_id)) FROM all_jira_okr_records_v2 WHERE type=0 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total AT-Found-Bug Tickets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(jira_id)) FROM all_jira_okr_records_v2 WHERE type=1 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Product Line Stats (Product Filter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<center><h1 style=\"color:rgb(87, 147, 242);\">Product Line (${productLine})</h1></center>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Test Case",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "GIt Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(DISTINCT(case)) FROM \"all_git_records_v2\" WHERE product='$productLine'  AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Executed Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter  GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE product='$productLine'  AND (\"status\"=0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE product='$productLine'  AND (\"status\"=1) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE product='$productLine'  AND (\"status\"=2) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pass Rate By Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CUMULATIVE_SUM(COUNT(\"case\")) FROM \"all_records_v2\" WHERE product='$productLine'  AND (\"status\"=0) AND $timeFilter GROUP BY time($interval) fill(null) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CUMULATIVE_SUM(COUNT(\"case\")) FROM \"all_records_v2\" WHERE product='$productLine'  AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Activity",
   "type": "table",
   "description": " '# of maintainers for this API / # of test cases for this API",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 11 },
   "targets": [
    {
     "alias": "Total",
     "query": "SELECT  api, case, maintainer FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter"
    }
   ]
  },
  {
   "title": "OKR Trends",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 11 },
   "targets": [
    {
     "alias": "AT Sign-off",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(DISTINCT(jira_id)) FROM \"all_jira_okr_records_v2\" WHERE product='$productLine'  AND (\"type\"=0) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "AT Found-bug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(DISTINCT(jira_id)) FROM \"all_jira_okr_records_v2\" WHERE product='$productLine'  AND  (\"type\"=1) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Cases Executed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Test Cases",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_git_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Count (Distinct)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter AND status=0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter AND status=1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter AND status=2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter AND status=0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE product='$productLine'  AND  $timeFilter AND status=1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE product='$productLine'  AND  $timeFilter AND status=2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Sign-off Tickets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(jira_id)) FROM all_jira_okr_records_v2 WHERE product='$productLine'  AND type=0 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total AT-Found-Bug Tickets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(jira_id)) FROM all_jira_okr_records_v2 WHERE product='$productLine'  AND type=1 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "options": { "content": " " },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 1 Maintainer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cases Executed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cases Contributions",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stability Analysis",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "alias": "Git Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Maintained Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Passed Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case, status FROM all_records_v2 WHERE product='$productLine'  AND status=0 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 1 Stability Score",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "Git Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Maintained Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Passed Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case, status FROM all_records_v2 WHERE product='$productLine'  AND status=0 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stability Score",
   "type": "stat",
   "description": "Only applicable for git cases >= 500",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "Git Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Maintained Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Passed Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case, status FROM all_records_v2 WHERE product='$productLine'  AND status=0 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 1 Git Contributor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cases In Git",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 1 Active Score",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Score",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_git_records_v2 WHERE product='$productLine'  AND  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  maintainer, case FROM all_records_v2 WHERE product='$productLine'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Individual Stats (QA Filter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<center><h1 style=\"color:rgb(87, 147, 242);\">Individual Contributions (${qa})</h1> \n</center>\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Cases Executed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(case) FROM all_git_records_v2 WHERE maintainer='$qa'  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Maintained Cases",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(DISTINCT(case)) FROM all_records_v2 WHERE maintainer='$qa'  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Pass Rate",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE maintainer='$qa'  AND (\"status\"=0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE maintainer='$qa'  AND (\"status\"=1) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"case\") FROM \"all_records_v2\" WHERE maintainer='$qa'  AND (\"status\"=2) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pass Rate By Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CUMULATIVE_SUM(COUNT(\"case\")) FROM \"all_records_v2\" WHERE maintainer='$qa'  AND (\"status\"=0) AND $timeFilter GROUP BY time($interval) fill(null) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CUMULATIVE_SUM(COUNT(\"case\")) FROM \"all_records_v2\" WHERE maintainer='$qa'  AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(case) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Execution Count (Distinct)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(case)) FROM all_records_v2 WHERE maintainer='$qa'  AND $timeFilter AND status=2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}